fragment GuideParts on Guide {
  __typename
  title
  region
  standfirst
  metaDescription
  heroImage
  heroAlt
  driveMinsFromLondon
  readTime
  mapLocation
  published
  quickFacts {
    __typename
    bestBase
    bestBasePrice
    bestBaseLink
    idealFor
    getThere
  }
  whyGo
  whereToStay
  whatToDo
  whereToEat
  itinerary
  proTips
  faq {
    __typename
    question
    answer
  }
  author
  authorNote
}
