//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  guide: Guide;
  guideConnection: GuideConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGuideArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGuideConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GuideFilter>;
};

export type DocumentFilter = {
  guide?: InputMaybe<GuideFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Guide | Folder;

export type GuideQuickFacts = {
  __typename?: 'GuideQuickFacts';
  bestBase?: Maybe<Scalars['String']['output']>;
  bestBasePrice?: Maybe<Scalars['String']['output']>;
  bestBaseLink?: Maybe<Scalars['String']['output']>;
  idealFor?: Maybe<Scalars['String']['output']>;
  getThere?: Maybe<Scalars['String']['output']>;
};

export type GuideFaq = {
  __typename?: 'GuideFaq';
  question?: Maybe<Scalars['String']['output']>;
  answer?: Maybe<Scalars['String']['output']>;
};

export type Guide = Node & Document & {
  __typename?: 'Guide';
  title: Scalars['String']['output'];
  region: Scalars['String']['output'];
  standfirst?: Maybe<Scalars['String']['output']>;
  metaDescription?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  heroAlt?: Maybe<Scalars['String']['output']>;
  driveMinsFromLondon?: Maybe<Scalars['Float']['output']>;
  readTime?: Maybe<Scalars['String']['output']>;
  published?: Maybe<Scalars['Boolean']['output']>;
  quickFacts?: Maybe<GuideQuickFacts>;
  whyGo?: Maybe<Scalars['JSON']['output']>;
  whereToStay?: Maybe<Scalars['JSON']['output']>;
  whatToDo?: Maybe<Scalars['JSON']['output']>;
  whereToEat?: Maybe<Scalars['JSON']['output']>;
  itinerary?: Maybe<Scalars['JSON']['output']>;
  proTips?: Maybe<Scalars['JSON']['output']>;
  faq?: Maybe<Array<Maybe<GuideFaq>>>;
  author?: Maybe<Scalars['String']['output']>;
  authorNote?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type GuideQuickFactsFilter = {
  bestBase?: InputMaybe<StringFilter>;
  bestBasePrice?: InputMaybe<StringFilter>;
  bestBaseLink?: InputMaybe<StringFilter>;
  idealFor?: InputMaybe<StringFilter>;
  getThere?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type GuideFaqFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type GuideFilter = {
  title?: InputMaybe<StringFilter>;
  region?: InputMaybe<StringFilter>;
  standfirst?: InputMaybe<StringFilter>;
  metaDescription?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  heroAlt?: InputMaybe<StringFilter>;
  driveMinsFromLondon?: InputMaybe<NumberFilter>;
  readTime?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
  quickFacts?: InputMaybe<GuideQuickFactsFilter>;
  whyGo?: InputMaybe<RichTextFilter>;
  whereToStay?: InputMaybe<RichTextFilter>;
  whatToDo?: InputMaybe<RichTextFilter>;
  whereToEat?: InputMaybe<RichTextFilter>;
  itinerary?: InputMaybe<RichTextFilter>;
  proTips?: InputMaybe<RichTextFilter>;
  faq?: InputMaybe<GuideFaqFilter>;
  author?: InputMaybe<StringFilter>;
  authorNote?: InputMaybe<StringFilter>;
};

export type GuideConnectionEdges = {
  __typename?: 'GuideConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Guide>;
};

export type GuideConnection = Connection & {
  __typename?: 'GuideConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GuideConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateGuide: Guide;
  createGuide: Guide;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateGuideArgs = {
  relativePath: Scalars['String']['input'];
  params: GuideMutation;
};


export type MutationCreateGuideArgs = {
  relativePath: Scalars['String']['input'];
  params: GuideMutation;
};

export type DocumentUpdateMutation = {
  guide?: InputMaybe<GuideMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  guide?: InputMaybe<GuideMutation>;
};

export type GuideQuickFactsMutation = {
  bestBase?: InputMaybe<Scalars['String']['input']>;
  bestBasePrice?: InputMaybe<Scalars['String']['input']>;
  bestBaseLink?: InputMaybe<Scalars['String']['input']>;
  idealFor?: InputMaybe<Scalars['String']['input']>;
  getThere?: InputMaybe<Scalars['String']['input']>;
};

export type GuideFaqMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type GuideMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  region?: InputMaybe<Scalars['String']['input']>;
  standfirst?: InputMaybe<Scalars['String']['input']>;
  metaDescription?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  heroAlt?: InputMaybe<Scalars['String']['input']>;
  driveMinsFromLondon?: InputMaybe<Scalars['Float']['input']>;
  readTime?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  quickFacts?: InputMaybe<GuideQuickFactsMutation>;
  whyGo?: InputMaybe<Scalars['JSON']['input']>;
  whereToStay?: InputMaybe<Scalars['JSON']['input']>;
  whatToDo?: InputMaybe<Scalars['JSON']['input']>;
  whereToEat?: InputMaybe<Scalars['JSON']['input']>;
  itinerary?: InputMaybe<Scalars['JSON']['input']>;
  proTips?: InputMaybe<Scalars['JSON']['input']>;
  faq?: InputMaybe<Array<InputMaybe<GuideFaqMutation>>>;
  author?: InputMaybe<Scalars['String']['input']>;
  authorNote?: InputMaybe<Scalars['String']['input']>;
};

export type GuidePartsFragment = { __typename: 'Guide', title: string, region: string, standfirst?: string | null, metaDescription?: string | null, heroImage?: string | null, heroAlt?: string | null, driveMinsFromLondon?: number | null, readTime?: string | null, published?: boolean | null, whyGo?: any | null, whereToStay?: any | null, whatToDo?: any | null, whereToEat?: any | null, itinerary?: any | null, proTips?: any | null, author?: string | null, authorNote?: string | null, quickFacts?: { __typename: 'GuideQuickFacts', bestBase?: string | null, bestBasePrice?: string | null, bestBaseLink?: string | null, idealFor?: string | null, getThere?: string | null } | null, faq?: Array<{ __typename: 'GuideFaq', question?: string | null, answer?: string | null } | null> | null };

export type GuideQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GuideQuery = { __typename?: 'Query', guide: { __typename: 'Guide', id: string, title: string, region: string, standfirst?: string | null, metaDescription?: string | null, heroImage?: string | null, heroAlt?: string | null, driveMinsFromLondon?: number | null, readTime?: string | null, published?: boolean | null, whyGo?: any | null, whereToStay?: any | null, whatToDo?: any | null, whereToEat?: any | null, itinerary?: any | null, proTips?: any | null, author?: string | null, authorNote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, quickFacts?: { __typename: 'GuideQuickFacts', bestBase?: string | null, bestBasePrice?: string | null, bestBaseLink?: string | null, idealFor?: string | null, getThere?: string | null } | null, faq?: Array<{ __typename: 'GuideFaq', question?: string | null, answer?: string | null } | null> | null } };

export type GuideConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GuideFilter>;
}>;


export type GuideConnectionQuery = { __typename?: 'Query', guideConnection: { __typename?: 'GuideConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GuideConnectionEdges', cursor: string, node?: { __typename: 'Guide', id: string, title: string, region: string, standfirst?: string | null, metaDescription?: string | null, heroImage?: string | null, heroAlt?: string | null, driveMinsFromLondon?: number | null, readTime?: string | null, published?: boolean | null, whyGo?: any | null, whereToStay?: any | null, whatToDo?: any | null, whereToEat?: any | null, itinerary?: any | null, proTips?: any | null, author?: string | null, authorNote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, quickFacts?: { __typename: 'GuideQuickFacts', bestBase?: string | null, bestBasePrice?: string | null, bestBaseLink?: string | null, idealFor?: string | null, getThere?: string | null } | null, faq?: Array<{ __typename: 'GuideFaq', question?: string | null, answer?: string | null } | null> | null } | null } | null> | null } };

export const GuidePartsFragmentDoc = gql`
    fragment GuideParts on Guide {
  __typename
  title
  region
  standfirst
  metaDescription
  heroImage
  heroAlt
  driveMinsFromLondon
  readTime
  published
  quickFacts {
    __typename
    bestBase
    bestBasePrice
    bestBaseLink
    idealFor
    getThere
  }
  whyGo
  whereToStay
  whatToDo
  whereToEat
  itinerary
  proTips
  faq {
    __typename
    question
    answer
  }
  author
  authorNote
}
    `;
export const GuideDocument = gql`
    query guide($relativePath: String!) {
  guide(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GuideParts
  }
}
    ${GuidePartsFragmentDoc}`;
export const GuideConnectionDocument = gql`
    query guideConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GuideFilter) {
  guideConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GuideParts
      }
    }
  }
}
    ${GuidePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      guide(variables: GuideQueryVariables, options?: C): Promise<{data: GuideQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GuideQueryVariables, query: string}> {
        return requester<{data: GuideQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GuideQueryVariables, query: string}, GuideQueryVariables>(GuideDocument, variables, options);
      },
    guideConnection(variables?: GuideConnectionQueryVariables, options?: C): Promise<{data: GuideConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GuideConnectionQueryVariables, query: string}> {
        return requester<{data: GuideConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GuideConnectionQueryVariables, query: string}, GuideConnectionQueryVariables>(GuideConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/45e6d8c4-b278-483f-827c-fb24f002ee6f/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  